prof_office:
- prof_office_shelf
- prof_office_shelf_0
- prof_office_desk_shared
- prof_office_office_chair
- prof_office_office_chair_0
- prof_office_office_chair_1
- prof_office_office_chair_2
- prof_office_office_chair_3
- prof_office_desk_prof
- prof_office_monitor_pc
- prof_office_monitor_pc_0
- prof_office_books
