ta2_sink:
  model: sink
  model_type: sdf
  position: [ 1.53230, 2.204468, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]
  
ta2_burner_stove:
  model: burner_stove
  model_type: sdf
  position: [ 2.868422, 2.205050, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]
  
ta2_table_ikea_bjursta:
  model: table_ikea_bjursta
  model_type: sdf
  position: [ 1.77236080355, -1.0, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]
    
ta2_chair_ikea_borje:
  model: chair_ikea_borje
  model_type: sdf
  position: [ 1.969930, 0.0, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]

ta2_couch:
  model: couch
  model_type: sdf
  position: [ -1.171137, -0.050618, 0.0 ]
  orientation: [ 0.0, 0.0, -1.57 ]

 
ta2_table_tv:
  model: table_tv
  model_type: sdf
  position: [ -3.507171, 0.0, 0.0 ]
  orientation: [ 0.0, 0.0, -1.57 ]

ta2_tv_samsung:
  model: tv_samsung
  model_type: sdf
  position: [ -3.431988, 0.0, 0.576413 ]
  orientation: [ 0.0, 0.0, 1.57 ]

