livingroom:
- ta2_sink
- ta2_burner_stove
- ta2_table_ikea_bjursta
- ta2_chair_ikea_borje
#- ta2_couch
- ta2_cabinet_ikea_malm_big
- ta2_milk
- ta2_salt
- ta2_tomato_sauce
- ta2_zwieback
- ta2_table_tv
- ta2_tv_samsung

