bed_king_1:
  model: bed_king_1
  model_type: sdf
  position: [ -4.5, 1.0, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]

table_round_1:
  model: table_round_1
  model_type: sdf
  position: [ -4.0, -3.0, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]

refrigerator_white_1:
  model: refrigerator_white_1
  model_type: sdf
  position: [ 4.5, -5.3, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]

stove_4burners_1:
  model: stove_4burners_1
  model_type: sdf
  position: [ 6.4, -3.5, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]

chair_modern_1:
  model: chair_modern_1
  model_type: sdf
  position: [ 4.5, 2.0, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]

chair_fancy_1:
  model: chair_fancy_1
  model_type: sdf
  position: [ -4.0, -1.5, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]

sofa_large_1:
  model: sofa_large_1
  model_type: sdf
  position: [ 0, -5.5, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]

shower_big_1:
  model: shower_big_1
  model_type: sdf
  position: [ 6.35, 4.55, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]

sink_big_1:
  model: sink_big_1
  model_type: sdf
  position: [ 3.5, 3.3, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]

toilet_white_1:
  model: toilet_white_1
  model_type: sdf
  position: [ 4.5, 5.7, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]

table_2person_1:
  model: table_2person_1
  model_type: sdf
  position: [ 4.5, 2.5, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]


