rococolab:
- rococolab_desk_shared
- rococolab_desk_shared_0
- rococolab_desk_shared_1
- rococolab_desk_shared_2
- rococolab_desk_shared_3
- rococolab_desk_shared_4
- rococolab_desk_shared_5
- rococolab_desk_shared_6
- rococolab_desk_shared_7
- rococolab_books
- rococolab_books_0
- rococolab_books_1
- rococolab_drawer
- rococolab_drawer_0
- rococolab_shelf
- rococolab_shelf_0
- rococolab_pc
- ignore_rococolab_grass_robocup
