kitchen:
- apartment_4_table_2person_1
- apartment_4_refrigerator_white_1
- apartment_4_chair_fancy_1
- apartment_4_chair_fancy_1_0
- apartment_4_chair_fancy_1_1
- apartment_4_drawer_kitchen_1
- apartment_4_drawer_kitchen_1_0
- apartment_4_microwave
- apartment_4_burner_stove
- apartment_4_sink
- apartment_4_trashcan
living_room:
- apartment_4_chair_foldable
- apartment_4_sofa_large_1
- apartment_4_table_round_1
- apartment_4_tv_samsung
- apartment_4_table_tv
corridor:
- apartment_4_rack_coat
- apartment_4_drawer

