table_2person_1:
  model: table_2person_1
  model_type: sdf
  position: [ 0.21, 3.31, 0.0 ]
  orientation: [ 0.0, 0.0, 1.57 ]
refrigerator_white_1:
  model: refrigerator_white_1
  model_type: sdf
  position: [ 2.4, 2.0, -0.13 ]
  orientation: [ 0.0, 0.0, 1.57 ]
chair_fancy_1:
  model: chair_fancy_1
  model_type: sdf
  position: [ 0.22, 4.36, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]
chair_fancy_1_0:
  model: chair_fancy_1
  model_type: sdf
  position: [ -0.59, 3.42, 0.0 ]
  orientation: [ 0.0, 0.0, 1.27 ]
chair_fancy_1_1:
  model: chair_fancy_1
  model_type: sdf
  position: [ 0.18, 2.19, 0.0 ]
  orientation: [ 0.0, 0.0, 2.47 ]
drawer_kitchen_1:
  model: drawer_kitchen_1
  model_type: sdf
  position: [ 2.45, 2.97, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]
drawer_kitchen_1_0:
  model: drawer_kitchen_1
  model_type: sdf
  position: [ 2.45, 5.17 , 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]
microwave:
  model: microwave
  model_type: sdf
  position: [ 2.31, 3.0, 0.92 ]
  orientation: [ 0.0, 0.0, 1.61 ]
burner_stove:
  model: burner_stove
  model_type: sdf
  position: [ 2.41, 4.0, 0.0 ]
  orientation: [ 0.0, 0.0, -1.57 ]
sink:
  model: sink
  model_type: sdf
  position: [ 1.38, 5.51, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]
trashcan:
  model: trashcan
  model_type: sdf
  position: [ 0.63, 5.66, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]

chair_foldable:
  model: chair_foldable
  model_type: sdf
  position: [ 5.13, -0.53, 0.0 ]
  orientation: [ 0.0, 0.0, -2.6 ]
sofa_large_1:
  model: sofa_large_1
  model_type: sdf
  position: [ 6.0, 1.4, 0.0 ]
  orientation: [ 0.0, 0.0, 1.57 ]
table_round_1:
  model: table_round_1
  model_type: sdf
  position: [ 4.92, 3.83, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]
tv_samsung:
  model: tv_samsung
  model_type: sdf
  position: [ 3.57, 1.82, 0.59 ]
  orientation: [ 0.0, 0.0, 1.7 ]
table_tv:
  model: table_tv
  model_type: sdf
  position: [ 3.5, 1.97, 0.0 ]
  orientation: [ 0.0, 0.0, -1.57 ]

rack_coat:
  model: rack_coat
  model_type: sdf
  position: [ -0.78, 1.07, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]
drawer:
  model: drawer
  model_type: sdf
  position: [ 0.77, -0.93, 0.0 ]
  orientation: [ 0.0, 0.0, 3.14 ]

bed:
  model: bed
  model_type: sdf
  position: [ 5.09, -1.86, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]
office_chair:
  model: office_chair
  model_type: sdf
  position: [ 5.75, -3.01, 0.0 ]
  orientation: [ 0.0, 0.0, 3.14 ]
desk_shared_0:
  model: desk_shared
  model_type: sdf
  position: [ 5.78, -3.89, 0.0 ]
  orientation: [ 0.0, 0.0, -1.54 ]

monitor_pc:
  model: monitor_pc
  model_type: sdf
  position: [ 0.54, -1.73, 0.80 ]
  orientation: [ 0.0, 0.0, -1.9 ]
desk_shared:
  model: desk_shared
  model_type: sdf
  position: [ 0.35, -1.84, 0.0 ]
  orientation: [ 0.0, 0.0, -1.54 ]
books:
  model: books
  model_type: sdf
  position: [ -0.23, -1.82, 0.76 ]
  orientation: [ 0.0, 0.0, 0.0 ]
chair_foldable_0:
  model: chair_foldable
  model_type: sdf
  position: [ 0.23, -2.50, 0.0 ]
  orientation: [ 0.0, 0.0, -3.14 ]
boxes:
  model: boxes
  model_type: sdf
  position: [ 0.98, -5.16, 0.0 ]
  orientation: [ 0.0, 0.0, 0.2 ]
bed_0:
  model: bed
  model_type: sdf
  position: [ -1.43, -4.67, 0.0 ]
  orientation: [ 0.0, 0.0, -1.55 ]

books_0:
  model: books
  model_type: sdf
  position: [ 4.51, -4.93, 0.77 ]
  orientation: [ 0.0, 0.0, 1.57 ]
desk_shared_1:
  model: desk_shared
  model_type: sdf
  position: [ 5.03, -4.94, 0.0 ]
  orientation: [ 0.0, 0.0, -1.57 ]
chair_modern_1:
  model: chair_modern_1
  model_type: sdf
  position: [ 5.18, -5.71, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]
bed_fullsize:
  model: bed_fullsize
  model_type: sdf
  position: [ 4.12, -7.6, 0.0 ]
  orientation: [ 0.0, 0.0, 1.57 ]

shower_small_1:
  model: shower_small_1
  model_type: sdf
  position: [ 1.35, -6.88, 0.0 ]
  orientation: [ 0.0, 0.0, 3.14 ]
sink_big_1:
  model: sink_big_1
  model_type: sdf
  position: [ 2.7, -7.17, 0.0 ]
  orientation: [ 0.0, 0.0, 1.57 ]
toilet_white_1:
  model: toilet_white_1
  model_type: sdf
  position: [ 2.58, -8.37, 0.0 ]
  orientation: [ 0.0, 0.0, -1.57 ]
