tables:
- restaurant_table_2people_0
- restaurant_table_2people_1
- restaurant_table_2people_2
- restaurant_table_4people_0
- restaurant_table_4people_1
- restaurant_table_4people_2
- restaurant_table_6people_0
- restaurant_table_6people_1
- restaurant_table_8people_0
- ignore_chair_ikea_0
- ignore_chair_ikea_1
- ignore_chair_ikea_2
- ignore_chair_ikea_3
- ignore_chair_ikea_4
- ignore_chair_ikea_5
- ignore_chair_ikea_6
- ignore_chair_ikea_7
- ignore_chair_ikea_8
- ignore_chair_ikea_9
- ignore_chair_ikea_10
- ignore_chair_ikea_11
- ignore_chair_ikea_12
- ignore_chair_ikea_13
- ignore_chair_ikea_14
- ignore_chair_ikea_15
- ignore_chair_ikea_16
- ignore_chair_ikea_17
- ignore_chair_ikea_18
- ignore_chair_ikea_19
- ignore_chair_ikea_20
- ignore_chair_ikea_21
- ignore_chair_ikea_22
- ignore_chair_ikea_23
- ignore_chair_ikea_24
- ignore_chair_ikea_25
- ignore_chair_ikea_26
- ignore_chair_ikea_27
- ignore_chair_ikea_28
- ignore_chair_ikea_29
- ignore_chair_ikea_30
- ignore_chair_ikea_31
- ignore_chair_ikea_32
- ignore_chair_ikea_33
- ignore_chair_ikea_34
- ignore_chair_ikea_35
- ignore_chair_ikea_36
- ignore_chair_ikea_37
- ignore_chair_ikea_38
reception:
- ignore_desk_shared_0
- ignore_desk_shared_1
- ignore_office_chair_0
- ignore_rack_coat_0
- ignore_rack_coat_1
