kitchen:
- sink
- burner_stove
- table_ikea_bjursta
- chair_ikea_borje

livingroom:
- couch
- table_living_room

bedroom:
- bed
- cabinet_ikea_malm_small

bathroom:
- bathroom_set

food:
- milk
- salt
- tomato_sauce
- zwieback
