car_blue_1:
  model: car_blue_1
  model_type: sdf
  position: [ 5.26, 4.82, 0.0 ]
  orientation: [ 0.0, 0.0, 1.57 ]

car_gray_1:
  model: car_gray_1
  model_type: sdf
  position: [ 5.13, -5.14, 0.0 ]
  orientation: [ 0.0, 0.0, 1.57 ]

car_gray_2:
  model: car_gray_2
  model_type: sdf
  position: [ 9.39, 5.66, 0.0 ]
  orientation: [ 0.0, 0.0, -1.6 ]

car_red_1:
  model: car_red_1
  model_type: sdf
  position: [ 9.99, -5.31, 0.0 ]
  orientation: [ 0.0, 0.0, 1.54 ]

car_white_1:
  model: car_white_1
  model_type: sdf
  position: [ 13.17, 5.08, 0.0 ]
  orientation: [ 0.0, 0.0, -1.58 ]


