phd_office_desk_shared:
  model: desk_shared
  model_type: sdf
  position: [ 5.21, -4.57, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]
phd_office_desk_shared_0:
  model: desk_shared
  model_type: sdf
  position: [ 5.21, -3.16, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]
phd_office_desk_shared_1:
  model: desk_shared
  model_type: sdf
  position: [ 5.21, -1.74, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]
phd_office_desk_shared_2:
  model: desk_shared
  model_type: sdf
  position: [ 2.96, -4.55, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]
phd_office_desk_shared_3:
  model: desk_shared
  model_type: sdf
  position: [ 2.96, -3.13, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]
phd_office_desk_shared_4:
  model: desk_shared
  model_type: sdf
  position: [ 0.97, -4.56, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]
phd_office_desk_shared_5:
  model: desk_shared
  model_type: sdf
  position: [ 0.97, -3.14, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]
phd_office_desk_shared_6:
  model: desk_shared
  model_type: sdf
  position: [ 0.97, -1.74, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]
phd_office_desk_shared_7:
  model: desk_shared
  model_type: sdf
  position: [ 2.96, -1.74, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]
phd_office_desk_shared_8:
  model: desk_shared
  model_type: sdf
  position: [ 0.10, -3.16, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]
phd_office_desk_shared_9:
  model: desk_shared
  model_type: sdf
  position: [ 0.10, -4.57, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]
phd_office_desk_shared_10:
  model: desk_shared
  model_type: sdf
  position: [ -1.28, -0.32, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]
phd_office_boxes:
  model: boxes
  model_type: sdf
  position: [ 5.19, 0.31, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]

phd_office_drawer:
  model: drawer
  model_type: sdf
  position: [ 2.07, 0.45, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]
phd_office_shelf:
  model: shelf
  model_type: sdf
  position: [ -0.02, -1.78, 0.0 ]
  orientation: [ 0.0, 0.0, 1.59 ]
phd_office_microwave:
  model: microwave
  model_type: sdf
  position: [ 1.88, 0.42, 0.67 ]
  orientation: [ 0.0, 0.0, 3.14 ]
phd_office_rack_coat:
  model: rack_coat
  model_type: sdf
  position: [ 5.20, -0.49, 0.0 ]
  orientation: [ 0.0, 0.0, 0.0 ]


phd_office_books:
  model: books
  model_type: sdf
  position: [ 2.52, 0.45, 0.67 ]
  orientation: [ 0.0, 0.0, 0.1 ]

