phdoffice:
- phd_office_desk_shared
- phd_office_desk_shared_0
- phd_office_desk_shared_1
- phd_office_desk_shared_2
- phd_office_desk_shared_3
- phd_office_desk_shared_4
- phd_office_desk_shared_5
- phd_office_desk_shared_6
- phd_office_desk_shared_7
- phd_office_desk_shared_8
- phd_office_desk_shared_9
- phd_office_desk_shared_10
- phd_office_boxes
- phd_office_drawer
- phd_office_shelf
- phd_office_microwave
- phd_office_rack_coat
- phd_office_books


